manchester_fighters/config/routes.rb
Rails.application.routes.draw do
      devise_for :users, controllers: {
        sessions: 'users/sessions', 
        registrations: 'users/registrations'
      }
  
  match 'fighters/show' => 'fighters#show', :via => :get
  match 'fighters/contact' => 'fighters#contact', :via => :get
  resources :fighters, :contacts, :about, :event_management

  root 'fighters#index'

end

manchester_fighters/app/models/fighter.rb
class Fighter < ActiveRecord::Base
  belongs_to :user

  has_attached_file :avatar, :styles => { :medium => "300x300#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

manchester_fighters/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_one :fighter

  accepts_nested_attributes_for :fighter     

  def fighter
    super || build_fighter
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, fighter_attributes: [:name, :avatar, :weight, :height, :experience, :id, :user_id])
  end

end

manchester_fighters/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

manchester_fighters/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :except => [:index, :show]
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

manchester_fighters/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
  end
end

manchester_fighters/app/controllers/event_management_controller.rb
class EventManagementController < ApplicationController
  def index
  end
end

manchester_fighters/app/controllers/fighters_controller.rb
class FightersController < ApplicationController
  def index
    @fighters = Fighter.all
  end

  def new
    @fighter = Fighter.new
  end
  
  def contact
    
  end

  def create 
    @fighter =  Fighter.create(fighter_params)
     if @rfighter.save
      redirect_to fighter_path
    else
      render :new
    end
    redirect_to '/fighters/show'
  end

  def show
    @fighters = Fighter.all
  end


private

  def set_fighter
    @fighter = Fighter.find(params[:id])
  end

  def fighter_params
    params.require(:fighter).permit(:name, :avatar, :weight, :height, :experience)
  end
end

manchester_fighters/app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

manchester_fighters/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

manchester_fighters/app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

manchester_fighters/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) {|u| 
    u.permit(:email, :password, :password_confirmation, fighter_attributes: [:name, :avatar, :weight, :height, :experience, :id, :user_id])}
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  
  # def after_sign_up_path_for(resource)
  #    case resource
  #   when :user, User
  #     resource.fighters? ? another_path : root_path
  #   else
  #     super
  #   end
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

manchester_fighters/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

manchester_fighters/app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

manchester_fighters/app/helpers/about_helper.rb
module AboutHelper
end

manchester_fighters/app/helpers/application_helper.rb
module ApplicationHelper
end

manchester_fighters/app/helpers/contacts_helper.rb
module ContactsHelper
end

manchester_fighters/app/helpers/event_management_helper.rb
module EventManagementHelper
end

manchester_fighters/app/helpers/fighters_helper.rb
module FightersHelper
end

manchester_fighters/app/views/about/index.html.erb
<!DOCTYPE html>
<html>
<head>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="/stylesheets/fighters.css">
</head>
<body class="about">
<p>Manchester Fighters is quickly establishing itself as the country’s premiere semi-professional boxing promotions company, for one reason: we take care of our fighters and our audience. We know that the most important part of any boxing event is the fight and  we will help you produce the most exciting bouts possible.</p>
<p>Supplying boxers to shows nationwide every week, Manchester Fighters has the biggest squad of enthusiastic and entertaining fighters in the North West. All our fighters are dedicated to boxing and love to put on a good show. We can match a boxer of any weight division and level of experience to fight at your show, anywhere in the country. </p>
<p>Manchester Fighters doesn’t make mis-matches. Only exciting, real fights to ignite the audience. If you’re looking for boxers to fight at your show, we have what you need, so get in <%= link_to 'contact', contacts_path,  method: :get%> with us.</p>
</body>
</html>

manchester_fighters/app/views/contacts/index.html.erb
<!DOCTYPE html>
<html>
<head>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="/stylesheets/fighters.css">
</head>
<body class="contacts">
<p>Call us on 07342 328 801 to find out further details and make arrangements.</p>
<p>Or e-mail your details and requirements to enquiry@manchesterfighters.com and we will contact you about the options we have available</p>
<div class="contact">
</div>
</body>
</html>

manchester_fighters/app/views/event_management/index.html.erb
<!DOCTYPE html>
<html>
<head>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="/stylesheets/fighters.scss">
</head>
<body class="events">
  <p>Interested in putting on a show? All you need is a venue. Manchester Fighters can handle  all other arrangements for you. From security to ring equipment, officials, mc’s and fighters. From a basic boxing showcase to an extravagant dinner show, we can provide a bespoke event tailored to suit your target audience and help you put on a great night of entertainment that people will remember.
  </p>
<div class="container-fluid-events">
  <img class="event_image" src="assets/rsz_boxing3.jpg">
</div>
</body>
</html>

manchester_fighters/app/views/fighters/index.html.erb
<!DOCTYPE html>
<html>
<head>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
 <link rel="stylesheet" href="/stylesheets/fighters.scss">
<link href='https://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
</head>
<body>
<div id="myCarousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
        <li data-target="#myCarousel" data-slide-to="5"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="assets/rsz_1fight3.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption carousel-caption1" >
              <h1 class="carousel-caption-h1">Dedicated</h1>
              <span><h3>Providing fighters nationwide</h3></span>
              <div>
              <%= button_to 'Book a fighter now', contacts_path, class:
              'jumbotron_button', method: :get %>
            </div>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="assets/me.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1 class="carousel-caption-h1">Reliable</h1>
              <h3>Fit, ready and always available</h3>
              <%= button_to 'Book a fighter now', contacts_path, class:
              'jumbotron_button', method: :get%>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="assets/hayden.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1 class="carousel-caption-h1">Disciplined</h1>
              <h3>Well trained and serious fighters</h3>
              <%= button_to 'Book a fighter now', contacts_path, class:
              'jumbotron_button', method: :get%>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="fourth-slide" src="assets/paul.jpg" alt="Fourth slide">
          <div class="container">
            <div class="carousel-caption">
              <h1 class="carousel-caption-h1">Entertaining</h1>
              <h3>All our fighters love to put on a show</h3>
              <%= button_to 'Book a fighter now', contacts_path, class:
              'jumbotron_button', method: :get%>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="fifth-slide" src="assets/rsz_11wheelan.jpg" alt="Fifth slide">
          <div class="container">
            <div class="carousel-caption">
              <h1 class="carousel-caption-h1">Exciting</h1>
              <h3>Guaranteed top-rate entertainment</h3>
              <%= button_to 'Book a fighter now', contacts_path, class:
              'jumbotron_button', method: :get%>
            </div>
          </div>
        </div>
         <div class="item">
          <img class="sixth-slide" src="assets/victory.jpg" alt="Sixth slide">
          <div class="container">
            <div class="carousel-caption">
              <h1 class="carousel-caption-h1">Join us</h1>
              <h3 class'all_welcome'>Become a Road Warrior today</h3>
              <%= button_to 'Register as a fighter', new_user_registration_path, class:
              'jumbotron_button', method: :get%>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    <div class="border">
    </div>
</body>
</html>

manchester_fighters/app/views/fighters/show.html.erb
<!DOCTYPE html>
<html>
<head>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="/stylesheets/fighters.scss">
</head>
<body>
  <div class="fighter_title"><h1 class="fighter_page">Our Fighters</h1>
    <h3>The Road Warriors</h3>
      <p>We have fighters from all weight divisions and of all levels of experience, from novice to expert, 
         ready to travel nationwide to put on the best show for you and your audience.
      </p>
  </div>
<div class="border">
  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <% else %>
    <div class="sign_in"><%= link_to "Sign in", new_user_session_path %></div>
  <% end %>
<div class="container-fluid">
  <div class="boxes">
    <% @fighters.each do |fighter| %>
      <div class="box"><h4><%=fighter.name%></h4>
        <%= image_tag fighter.avatar.url(:medium), class:"profile_circle" %>
      </br>
        Weight: <%= fighter.weight %>
      <br>
        Height: <%= fighter.height %></div>
    <%end%>
 </div>
</div>
</body>
</html>

manchester_fighters/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Manchester Fighters</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  
  
   <link rel="stylesheet" href="/stylesheets/application.scss">
</head>
<body>

 
  <div id='header_logo' class="container-fluid-header">
  <%= link_to image_tag("/assets/rsz_1rsz_1logo1.png"), root_path, class: "header_logo"  %>
  </div>
  
  
 <div>
  <ul class="topnav">
  <li class="active mf"><%= link_to 'Manchester Fighters', root_path,  method: :get%></li>
  <li><%= link_to 'About', about_index_path,  method: :get%></li>
  <li><%= link_to 'Fighters', fighters_show_path %></li>
  <li><%= link_to 'Event management', event_management_index_path,  method: :get%></li>
  <li><%= link_to 'Register as a fighter', new_user_registration_path,  method: :get%></li>
  <li><%= link_to 'Contact', contacts_path,  method: :get%></li>
  
  <li class="icon">
    <a href="javascript:void(0);" style="font-size:15px;" onclick="myFunction()">☰</a>
  </li>
</ul>



 </div>
 <div class="border">
 </div>



<%= yield %>


<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div id="footer">
      <br>

      Follow us: 
      <a target="_blank" title="follow me on facebook" href="https://www.facebook.com/groups/585152941597556/?fref=ts"><img alt="follow me on facebook" src="https://c866088.ssl.cf3.rackcdn.com/assets/facebook40x40.png" border=0></a>
      <a target="_blank" title="follow me on instagram" href="https://www.instagram.com/manchester_fighters/"><img alt="follow me on instagram" src="https://c866088.ssl.cf3.rackcdn.com/assets/instagram40x40.png" border=0></a>
      <a target="_blank" title="follow me on Twitter" href="https://twitter.com/mancfighters"><img alt="follow me on twitter" src="https://c866088.ssl.cf3.rackcdn.com/assets/twitter40x40.png" border=0></a>
      <br>
      <br>
      Manchester Fighters © 2016
      <br>
      <br>
   </div>
  
<script>
function myFunction() {
    document.getElementsByClassName("topnav")[0].classList.toggle("responsive");
}
</script>

</body>
</html>